//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAGConfigEx2 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAGConfigEx2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 行号模式（推荐） 的本地化字符串。
        /// </summary>
        internal static string AutoLabel_LineNumber {
            get {
                return ResourceManager.GetString("AutoLabel_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时标签模式 的本地化字符串。
        /// </summary>
        internal static string AutoLabel_TempLabel {
            get {
                return ResourceManager.GetString("AutoLabel_TempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CD音轨 的本地化字符串。
        /// </summary>
        internal static string BGM_CDDA {
            get {
                return ResourceManager.GetString("BGM_CDDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI文件 的本地化字符串。
        /// </summary>
        internal static string BGM_MIDI {
            get {
                return ResourceManager.GetString("BGM_MIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 波形文件 的本地化字符串。
        /// </summary>
        internal static string BGM_Wave {
            get {
                return ResourceManager.GetString("BGM_Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 256色 的本地化字符串。
        /// </summary>
        internal static string Color_EightBit {
            get {
                return ResourceManager.GetString("Color_EightBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 24位色 的本地化字符串。
        /// </summary>
        internal static string Color_TwentyFourBit {
            get {
                return ResourceManager.GetString("Color_TwentyFourBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件  (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像文件  (*.BMP;*.JPG;*.PNG;*.TLG)|*.BMP;*.JPG;*.PNG;*.TLG 的本地化字符串。
        /// </summary>
        internal static string FileFilter_Images {
            get {
                return ResourceManager.GetString("FileFilter_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标指针   (*.CUR;*.ANI)|*.CUR;*.ANI 的本地化字符串。
        /// </summary>
        internal static string FileFilter_MouseCursor {
            get {
                return ResourceManager.GetString("FileFilter_MouseCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体图形文件   (*.TFT)|*.TFT 的本地化字符串。
        /// </summary>
        internal static string FileFilter_PreRenderedFonts {
            get {
                return ResourceManager.GetString("FileFilter_PreRenderedFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可存档标签处记录 的本地化字符串。
        /// </summary>
        internal static string HistRecord_AtLabels {
            get {
                return ResourceManager.GetString("HistRecord_AtLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项分支时记录 的本地化字符串。
        /// </summary>
        internal static string HistRecord_AtSelection {
            get {
                return ResourceManager.GetString("HistRecord_AtSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动记录 的本地化字符串。
        /// </summary>
        internal static string HistRecord_Manually {
            get {
                return ResourceManager.GetString("HistRecord_Manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特殊模式 的本地化字符串。
        /// </summary>
        internal static string Message_ltAddAlpha {
            get {
                return ResourceManager.GetString("Message_ltAddAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兼容模式 的本地化字符串。
        /// </summary>
        internal static string Message_ltAlpha {
            get {
                return ResourceManager.GetString("Message_ltAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩 的本地化字符串。
        /// </summary>
        internal static string Save_Compressed {
            get {
                return ResourceManager.GetString("Save_Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密 的本地化字符串。
        /// </summary>
        internal static string Save_Encrypted {
            get {
                return ResourceManager.GetString("Save_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 普通 的本地化字符串。
        /// </summary>
        internal static string Save_Normal {
            get {
                return ResourceManager.GetString("Save_Normal", resourceCulture);
            }
        }
    }
}
