//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAGConfigEx2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KAGConfigEx2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行号模式（推荐）.
        /// </summary>
        internal static string AutoLabel_LineNumber {
            get {
                return ResourceManager.GetString("AutoLabel_LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 临时标签模式.
        /// </summary>
        internal static string AutoLabel_TempLabel {
            get {
                return ResourceManager.GetString("AutoLabel_TempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD音轨.
        /// </summary>
        internal static string BGM_CDDA {
            get {
                return ResourceManager.GetString("BGM_CDDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI文件.
        /// </summary>
        internal static string BGM_MIDI {
            get {
                return ResourceManager.GetString("BGM_MIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 波形文件.
        /// </summary>
        internal static string BGM_Wave {
            get {
                return ResourceManager.GetString("BGM_Wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256色.
        /// </summary>
        internal static string Color_EightBit {
            get {
                return ResourceManager.GetString("Color_EightBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24位色.
        /// </summary>
        internal static string Color_TwentyFourBit {
            get {
                return ResourceManager.GetString("Color_TwentyFourBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有文件  (*.*)|*.*.
        /// </summary>
        internal static string FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像文件  (*.BMP;*.JPG;*.PNG;*.TLG)|*.BMP;*.JPG;*.PNG;*.TLG.
        /// </summary>
        internal static string FileFilter_Images {
            get {
                return ResourceManager.GetString("FileFilter_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鼠标指针   (*.CUR;*.ANI)|*.CUR;*.ANI.
        /// </summary>
        internal static string FileFilter_MouseCursor {
            get {
                return ResourceManager.GetString("FileFilter_MouseCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字体图形文件   (*.TFT)|*.TFT.
        /// </summary>
        internal static string FileFilter_PreRenderedFonts {
            get {
                return ResourceManager.GetString("FileFilter_PreRenderedFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可存档标签处记录.
        /// </summary>
        internal static string HistRecord_AtLabels {
            get {
                return ResourceManager.GetString("HistRecord_AtLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选项分支时记录.
        /// </summary>
        internal static string HistRecord_AtSelection {
            get {
                return ResourceManager.GetString("HistRecord_AtSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 手动记录.
        /// </summary>
        internal static string HistRecord_Manually {
            get {
                return ResourceManager.GetString("HistRecord_Manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特殊模式.
        /// </summary>
        internal static string Message_ltAddAlpha {
            get {
                return ResourceManager.GetString("Message_ltAddAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 兼容模式.
        /// </summary>
        internal static string Message_ltAlpha {
            get {
                return ResourceManager.GetString("Message_ltAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 压缩.
        /// </summary>
        internal static string Save_Compressed {
            get {
                return ResourceManager.GetString("Save_Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加密.
        /// </summary>
        internal static string Save_Encrypted {
            get {
                return ResourceManager.GetString("Save_Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 普通.
        /// </summary>
        internal static string Save_Normal {
            get {
                return ResourceManager.GetString("Save_Normal", resourceCulture);
            }
        }
    }
}
